import React from 'react';

export default function ReportPreview({ reportRef, displaySales, displaySalesData, displayStats, formatCurrency, formatDate, user }) {
  return (
    <div
      ref={reportRef}
      style={{
        position: 'fixed',
        left: '-10000px',
        top: 0,
        width: '794px',
        background: '#ffffff',
        color: '#064e3b',
        padding: '28px',
        boxSizing: 'border-box',
        fontFamily: 'Inter, ui-sans-serif, system-ui, -apple-system, "Segoe UI", Roboto, "Helvetica Neue", Arial',
        lineHeight: 1.3,
      }}
    >
      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: 12 }}>
        <div>
          <h1 style={{ margin: 0, color: '#065f46', fontSize: 22, fontWeight: 800 }}>AgriLink — Portfolio Report</h1>
          <div style={{ marginTop: 6, color: '#065f46', fontWeight: 700 }}>{user?.name || user?.email || 'Farmer'}</div>
        </div>
        <div style={{ textAlign: 'right' }}>
          <div style={{ fontSize: 12, color: '#065f46', fontWeight: 700 }}>{new Date().toLocaleDateString()}</div>
          <div style={{ fontSize: 11, color: '#065f46' }}>Generated by AgriLink</div>
        </div>
      </div>

      <hr style={{ border: 'none', borderTop: '2px solid #d1fae5', margin: '8px 0 18px' }} />

      <div style={{ display: 'flex', gap: 16, marginBottom: 20 }}>
        <div style={{ flex: 1, padding: 12, background: '#ecfdf5', borderRadius: 8, border: '1px solid #bbf7d0' }}>
          <div style={{ fontSize: 12, color: '#065f46', fontWeight: 800 }}>Total Value</div>
          <div style={{ fontSize: 18, fontWeight: 900 }}>{formatCurrency(displaySales.reduce((sum, item) => sum + (item.price * item.weight), 0))}</div>
        </div>
        <div style={{ flex: 1, padding: 12, background: '#fff7ed', borderRadius: 8, border: '1px solid #ffedd5' }}>
          <div style={{ fontSize: 12, color: '#92400e', fontWeight: 800 }}>Total Quantity</div>
          <div style={{ fontSize: 18, fontWeight: 900 }}>{displaySales.reduce((sum, item) => sum + item.weight, 0)} {displaySales[0]?.quantityUnit || 'kg'}</div>
        </div>
        <div style={{ flex: 1, padding: 12, background: '#eef2ff', borderRadius: 8, border: '1px solid #e0e7ff' }}>
          <div style={{ fontSize: 12, color: '#3730a3', fontWeight: 800 }}>Transactions</div>
          <div style={{ fontSize: 18, fontWeight: 900 }}>{displaySales.length}</div>
        </div>
      </div>

      <div style={{ marginTop: 6 }}>
        <table style={{ width: '100%', borderCollapse: 'collapse', fontSize: 12 }}>
          <thead>
            <tr>
              <th style={{ textAlign: 'left', padding: '8px 6px', borderBottom: '2px solid #e6f9ef', color: '#065f46' }}>Item</th>
              <th style={{ textAlign: 'right', padding: '8px 6px', borderBottom: '2px solid #e6f9ef', color: '#065f46' }}>Price/kg</th>
              <th style={{ textAlign: 'right', padding: '8px 6px', borderBottom: '2px solid #e6f9ef', color: '#065f46' }}>Quantity</th>
              <th style={{ textAlign: 'right', padding: '8px 6px', borderBottom: '2px solid #e6f9ef', color: '#065f46' }}>Date</th>
              <th style={{ textAlign: 'right', padding: '8px 6px', borderBottom: '2px solid #e6f9ef', color: '#065f46' }}>Total</th>
              <th style={{ textAlign: 'right', padding: '8px 6px', borderBottom: '2px solid #e6f9ef', color: '#065f46' }}>Status</th>
            </tr>
          </thead>
          <tbody>
            {displaySales.map((sale, idx) => (
              <tr key={sale.id} style={{ background: idx % 2 === 0 ? 'transparent' : '#f8fffb' }}>
                <td style={{ padding: '10px 6px', verticalAlign: 'top', color: '#065f46', fontWeight: 700 }}>{sale.item}</td>
                <td style={{ padding: '10px 6px', verticalAlign: 'top', textAlign: 'right', color: '#065f46' }}>₹{sale.price}</td>
                <td style={{ padding: '10px 6px', verticalAlign: 'top', textAlign: 'right', color: '#065f46' }}>{sale.weight} {sale.quantityUnit}</td>
                <td style={{ padding: '10px 6px', verticalAlign: 'top', textAlign: 'right', color: '#065f46' }}>{formatDate(sale.time)}</td>
                <td style={{ padding: '10px 6px', verticalAlign: 'top', textAlign: 'right', color: '#065f46', fontWeight: 800 }}>{formatCurrency(sale.price * sale.weight)}</td>
                <td style={{ padding: '10px 6px', verticalAlign: 'top', textAlign: 'right' }}>{sale.status === 'completed' ? 'Completed' : 'Pending'}</td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>

      <div style={{ marginTop: 22, display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
        <div style={{ fontSize: 11, color: '#6b7280' }}>AgriLink • Professional Report</div>
        <div style={{ fontSize: 11, color: '#6b7280' }}>Page 1</div>
      </div>
    </div>
  );
}
