import { Inter } from "next/font/google";
import "./globals.css";
import { CivicAuthProvider } from "@civic/auth/nextjs";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "AgriLink",
  description: "Generated by create next app",
  icons: {
    icon: "/agrilink.png", // Add this
  },
};

import { ReactNode } from "react";

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <script src="https://js.puter.com/v2/" />
      </head>
      <body className={inter.className}>
        <CivicAuthProvider>
          {children}
        </CivicAuthProvider>
      </body>
    </html>
  );
}
